# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.firs)ribute.create(name: "poop", age: 6, gender: "m", alive: true, district_id: 1)
District.delete_all
Citizen.delete_all
Round.delete_all
Game.delete_all

#game
	Game.create(name: "Hungerful Treatise")

#rounds
	Round.create(name: "Round 1")
	Round.create(name: "Round 2")
	Round.create(name: "Round 3")
	Round.create(name: "Round 4")
	Round.create(name: "Round 5")

#districts
	District.create(name: "District One")
	District.create(name: "District Two")
	District.create(name: "District Three")
	District.create(name: "District Four")
	District.create(name: "District Five")
	District.create(name: "District Six")
	District.create(name: "District Seven")
	District.create(name: "District Eight")
	District.create(name: "District Nine")
	District.create(name: "District Ten")
	District.create(name: "District Eleven")
	District.create(name: "District Twelve")

#citizen
Citizen.create(name: "doop", age: 18, gender: "m", alive: true, district_id: 1)
Citizen.create(name: "snoop", age: 5, gender: "f", alive: true, district_id: 1)
Citizen.create(name: "boop", age: 18, gender: "f", alive: true, district_id: 1)
Citizen.create(name: "dowop", age: 18, gender: "m", alive: true, district_id: 2)
Citizen.create(name: "bowop", age: 18, gender: "f", alive: true, district_id: 2)
Citizen.create(name: "doeop", age: 18, gender: "m", alive: true, district_id: 3)
Citizen.create(name: "borop", age: 18, gender: "f", alive: true, district_id: 3)
Citizen.create(name: "dtoop", age: 18, gender: "m", alive: true, district_id: 4)
Citizen.create(name: "bofop", age: 18, gender: "f", alive: true, district_id: 4)
Citizen.create(name: "doogp", age: 18, gender: "m", alive: true, district_id: 5)
Citizen.create(name: "bosop", age: 18, gender: "f", alive: true, district_id: 5)
Citizen.create(name: "doaop", age: 18, gender: "m", alive: true, district_id: 6)
Citizen.create(name: "boyop", age: 18, gender: "f", alive: true, district_id: 6)
Citizen.create(name: "doolp", age: 18, gender: "m", alive: true, district_id: 7)
Citizen.create(name: "boowp", age: 18, gender: "f", alive: true, district_id: 7)
Citizen.create(name: "dortop", age: 18, gender: "m", alive: true, district_id: 8)
Citizen.create(name: "boosfp", age: 18, gender: "f", alive: true, district_id: 8)
Citizen.create(name: "doosrp", age: 18, gender: "m", alive: true, district_id: 9)
Citizen.create(name: "bongop", age: 18, gender: "f", alive: true, district_id: 9)
Citizen.create(name: "doocsdp", age: 18, gender: "m", alive: true, district_id: 10)
Citizen.create(name: "booasdap", age: 18, gender: "f", alive: true, district_id: 10)
Citizen.create(name: "doasop", age: 18, gender: "m", alive: true, district_id: 11)
Citizen.create(name: "bogtop", age: 18, gender: "f", alive: true, district_id: 11)
Citizen.create(name: "doqwop", age: 18, gender: "m", alive: true, district_id: 12)
Citizen.create(name: "bojhop", age: 18, gender: "f", alive: true, district_id: 12)
Citizen.create(name: "lobop", age: 20, gender: "f", alive: true, district_id: 1)
Citizen.create(name: "loocxp", age: 20, gender: "f", alive: true, district_id: 2)
Citizen.create(name: "loosp", age: 20, gender: "f", alive: true, district_id: 3)
Citizen.create(name: "loooiyp", age: 20, gender: "f", alive: true, district_id: 4)
Citizen.create(name: "lodfop", age: 20, gender: "f", alive: true, district_id: 5)
Citizen.create(name: "losfdgsdop", age: 20, gender: "f", alive: true, district_id: 6)
Citizen.create(name: "loocxp", age: 20, gender: "f", alive: true, district_id: 7)
Citizen.create(name: "loxcop", age: 20, gender: "f", alive: true, district_id: 8)
Citizen.create(name: "lodrop", age: 20, gender: "f", alive: true, district_id: 9)
Citizen.create(name: "losop", age: 20, gender: "f", alive: true, district_id: 10)
Citizen.create(name: "lowrtop", age: 20, gender: "f", alive: true, district_id: 11)
Citizen.create(name: "lomjhop", age: 20, gender: "f", alive: true, district_id: 12)
Citizen.create(name: "doefoefp", age: 18, gender: "m", alive: true, district_id: 1)
Citizen.create(name: "snoefoefp", age: 5, gender: "f", alive: true, district_id: 1)
Citizen.create(name: "boefoefp", age: 18, gender: "f", alive: true, district_id: 1)
Citizen.create(name: "doefwoefp", age: 14, gender: "m", alive: true, district_id: 2)
Citizen.create(name: "boefwoefp", age: 14, gender: "f", alive: true, district_id: 2)
Citizen.create(name: "doefeoefp", age: 14, gender: "m", alive: true, district_id: 3)
Citizen.create(name: "boefroefp", age: 14, gender: "f", alive: true, district_id: 3)
Citizen.create(name: "dtoefoefp", age: 14, gender: "m", alive: true, district_id: 4)
Citizen.create(name: "boeffoefp", age: 14, gender: "f", alive: true, district_id: 4)
Citizen.create(name: "doefoefgp", age: 16, gender: "m", alive: true, district_id: 5)
Citizen.create(name: "boefsoefp", age: 16, gender: "f", alive: true, district_id: 5)
Citizen.create(name: "doefaoefp", age: 16, gender: "m", alive: true, district_id: 6)
Citizen.create(name: "boefyoefp", age: 16, gender: "f", alive: true, district_id: 6)
Citizen.create(name: "doefoeflp", age: 18, gender: "m", alive: true, district_id: 7)
Citizen.create(name: "boefoefwp", age: 18, gender: "f", alive: true, district_id: 7)
Citizen.create(name: "doefrtoefp", age: 18, gender: "m", alive: true, district_id: 8)
Citizen.create(name: "boefoefsfp", age: 13, gender: "f", alive: true, district_id: 8)
Citizen.create(name: "doefoefsrp", age: 13, gender: "m", alive: true, district_id: 9)
Citizen.create(name: "boefngoefp", age: 13, gender: "f", alive: true, district_id: 9)
Citizen.create(name: "doefoefcsdp", age: 18, gender: "m", alive: true, district_id: 10)
Citizen.create(name: "boefoefasdap", age: 18, gender: "f", alive: true, district_id: 10)
Citizen.create(name: "doefasoefp", age: 18, gender: "m", alive: true, district_id: 11)
Citizen.create(name: "boefgtoefp", age: 18, gender: "f", alive: true, district_id: 11)
Citizen.create(name: "doefqwoefp", age: 18, gender: "m", alive: true, district_id: 12)
Citizen.create(name: "boefjhoefp", age: 18, gender: "f", alive: true, district_id: 12)
Citizen.create(name: "loefboefp", age: 50, gender: "f", alive: true, district_id: 1)
Citizen.create(name: "loefoefcxp", age: 43, gender: "m", alive: true, district_id: 2)
Citizen.create(name: "loefoefsp", age: 22, gender: "m", alive: true, district_id: 3)
Citizen.create(name: "loefoefoefiyp", age: 30, gender: "m", alive: true, district_id: 4)
Citizen.create(name: "loefdfoefp", age: 70, gender: "m", alive: true, district_id: 5)
Citizen.create(name: "loefsfdgsdoefp", age: 20, gender: "m", alive: true, district_id: 6)
Citizen.create(name: "loefoefcxp", age: 26, gender: "f", alive: true, district_id: 7)
Citizen.create(name: "loefxcoefp", age: 28, gender: "f", alive: true, district_id: 8)
Citizen.create(name: "loefdroefp", age: 20, gender: "f", alive: true, district_id: 9)
Citizen.create(name: "loefsoefp", age: 26, gender: "f", alive: true, district_id: 10)
Citizen.create(name: "loefwrtoefp", age: 40, gender: "f", alive: true, district_id: 11)
Citizen.create(name: "loefmjhop", age: 20, gender: "f", alive: true, district_id: 12)